apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: argocd
  labels:
    app: argocd
spec:
  replicas: 3  
  selector:
    matchLabels:
      app:  myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: httpd  
          ports:
            - containerPort: 80
          env:
            - name: ENV
              value: "production"  
          resources:  
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP 
