
apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyApp
  namespace: argocd
  labels:
    app: argocd
spec:
  replicas: 3  
  selector:
    matchLabels:
      app:  Myapp
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
        - name: Myapp
          image: OsherAPP  
          ports:
            - containerPort: 80
          env:
            - name: ENV
              value: "production"  
          resources:  
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: MyApp
  namespace: <NAMESPACE>
  labels:
    app: MyApp
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 
