name: Test and Deploy Python App with Argo CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest tests/
        continue-on-error: false  # This fails the workflow if tests fail

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Runs only if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Argo CD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Login to Argo CD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        run: |
          argocd login $ARGOCD_SERVER --insecure --auth-token $ARGOCD_AUTH_TOKEN

      - name: Sync Argo CD Application
        run: argocd app sync my-app  # Replace "my-app" with your Argo CD app name

      - name: Wait for Argo CD App to Sync
        run: argocd app wait my-app --sync