name: Deploy to Argo CD

on:
  push:
    branches:
      - main  # Deploy only on changes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the version appropriate for your project

      - name: Install dependencies
        run: |
          npm install  # Install dependencies for JavaScript/Node.js projects

      - name: Run Unit Tests
        run: |
          npm test  # Run tests defined in package.json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies for Python projects

      - name: Run Python Tests
        run: |
          pytest  # Run Python tests using pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Only runs if the test job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Argo CD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Login to Argo CD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        run: |
          argocd login $ARGOCD_SERVER --insecure --auth-token $ARGOCD_AUTH_TOKEN

      - name: Sync Argo CD Application
        run: |
          # Replace "my-app" with your Argo CD application name
          argocd app sync my-app

      - name: Wait for Argo CD App to Sync
        run: |
          # Replace "my-app" with your Argo CD application name
          argocd app wait my-app --sync