apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-workflow-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: clone-repo
        template: clone
    - - name: run-tests
        template: test
    - - name: build-image
        template: build
    - - name: push-to-dockerhub
        template: push

  - name: clone
    container:
      image: alpine/git
      command: ["sh", "-c"]
      args: ["git clone https://github.com/yourusername/yourrepo.git && cd yourrepo"]

  - name: test
    container:
      image: python:3.9
      command: ["sh", "-c"]
      args: ["cd yourrepo && pytest ."]

  - name: build
    container:
      image: docker:20.10
      env:
        - name: DOCKER_BUILDKIT
          value: "1"
      command: ["sh", "-c"]
      args: ["cd yourrepo && docker build -t yourusername/yourrepo:latest ."]

  - name: push
    container:
      image: docker:20.10
      env:
        - name: DOCKER_BUILDKIT
          value: "1"
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: docker-credentials
              key: username
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docker-credentials
              key: password
      command: ["sh", "-c"]
      args: ["docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push yourusername/yourrepo:latest"]
