name: Validate GitHub Actions Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Environment
      run: |
        # Example setup for a Node.js application
        npm ci
        
    - name: Run Unit Tests
      run: npm test
        
    - name: Run Integration Tests  
      run: npm run test:integration
        
    - name: Run End-to-End (E2E) Tests
      run: npm run test:e2e
        
    - name: Run Code Linting
      run: npm run lint
        
    - name: Run Code Coverage
      run: npm run test:coverage
        
    - name: Upload Code Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Verify Test Results
      run: |
        # Check if all tests passed
        if [ $? -ne 0 ]; then
          echo "One or more tests failed!"
          exit 1
        else
          echo "All tests passed!"
        fi